
export const GET_DATA = 'GET_DATA';
export const GET_DATA_SUCCESSFUL = 'GET_DATA_SUCCESSFUL';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

export const GET_ADDRESS = 'GET_ADDRESS';
export const GET_ADDRESS_SUCCESSFUL = 'GET_ADDRESS_SUCCESSFUL';
export const GET_ADDRESS_FAILURE = 'GET_ADDRESS_FAILURE';

export const POST_ADDRESS_SUCCESS = 'POST_ADDRESS_SUCCESS';
