export const ADD_TO_CART="ADD_TO_CART"
export const ADD_PAYMENT_DETAILS="ADD_PAYMENT_DETAILS"
export const UPDATE_CART="UPDATE_CART"
export const PLACE_ORDER_REQUEST="PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS="PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAILURE="PLACE_ORDER_FAILURE"



